### ISSUE TITLE
Copied into RPI, worked then stopped

### ISSUE THREAD

**Issue by GonsterMacher** [avipars/pi-cam-server#1]
<img width="893" alt="Pi-Cam2" src="https://github.com/user-attachments/assets/35039138-bbb7-43f2-a747-17d09261d321">
<img width="1300" alt="Pi-Cam1" src="https://github.com/user-attachments/assets/59899456-3915-475d-9765-3efc47fcf0a2">

I can't tell if the screen captures came through.

I copied the code into MU in my Pi, ran it and it worked.  I made no changes.  Fails in Firefox, Chrome, Safari, and Brave. 

I'm a noob and completely lost if nothing changed (that I know of) and what worked stops working!
 
Thanks in advance,
John Merantza merantza@gmail.com

<img width="1300" alt="Pi-Cam1" src="https://github.com/user-attachments/assets/005757b2-40bc-4ed8-9d37-8eb8f247c50d">
<img width="893" alt="Pi-Cam2" src="https://github.com/user-attachments/assets/08125405-a691-4154-a807-36056a491e0a">

**Comment by avipars** [comment]
You need a colon before the port number and not a slash, additionally ssl hasn't been set up for this project, so use http

try http://192.168.40.112:8000

**Comment by avipars** [comment]
Closing as this issue isn't related directly to the project
